options:
  sendgrid-creds:
    type: string
    default: ""
    description: |
      username:password for sendgrid account
  email-recipient:
    type: string
    default: ""
    description: |
      Recipient of emails from luigi-server
